#ifndef READ_HPP
#define READ_HPP

inline const char* var1 =
    "Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus "
    "ex sapien vitae pellentesque sem placerat in id cursus mi pretium tellus "
    "duis convallis tempus leo eu aenean sed diam urna tempor pulvinar vivamus "
    "fringilla lacus nec metus bibendum egestas iaculis massa nisl malesuada "
    "lacinia integer nunc posuere ut hendrerit semper vel class aptent taciti "
    "sociosqu ad litora torquent per conubia nostra inceptos himenaeos orci "
    "varius natoque penatibus et magnis dis parturient montes nascetur "
    "ridiculus mus donec rhoncus eros lobortis nulla molestie mattis "
    "scelerisque maximus eget fermentum odio phasellus non purus est efficitur "
    "laoreet mauris pharetra vestibulum fusce dictum risus blandit quis "
    "suspendisse aliquet nisi sodales consequat magna ante condimentum neque "
    "at luctus nibh finibus facilisis dapibus etiam interdum tortor ligula "
    "congue sollicitudin erat viverra ac tincidunt nam porta elementum a enim "
    "euismod quam justo lectus commodo augue arcu dignissim velit aliquam "
    "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum gravida "
    "cras eleifend turpis fames primis vulputate ornare sagittis vehicula "
    "praesent dui felis venenatis ultrices proin libero feugiat tristique "
    "accumsan maecenas potenti ultricies habitant morbi senectus netus "
    "suscipit auctor curabitur facilisi cubilia curae hac habitasse platea "
    "dictumst lorem ipsum dolor sit amet consectetur adipiscing elit quisque "
    "faucibus ex sapien vitae pellentesque sem placerat in id cursus mi "
    "pretium tellus duis convallis tempus leo eu aenean sed diam urna tempor "
    "pulvinar vivamus fringilla lacus nec metus bibendum egestas iaculis massa "
    "nisl malesuada lacinia integer nunc posuere ut hendrerit semper vel class "
    "aptent taciti sociosqu ad litora torquent per conubia nostra inceptos "
    "himenaeos orci varius natoque penatibus et magnis dis parturient montes "
    "nascetur ridiculus mus donec rhoncus eros lobortis nulla molestie mattis "
    "scelerisque maximus eget fermentum odio phasellus non purus est efficitur "
    "laoreet mauris pharetra vestibulum fusce dictum risus blandit quis "
    "suspendisse aliquet nisi sodales consequat magna ante condimentum neque "
    "at luctus nibh finibus facilisis dapibus etiam interdum tortor ligula "
    "congue sollicitudin erat viverra ac tincidunt nam porta elementum a enim "
    "euismod quam justo lectus commodo augue arcu dignissim velit aliquam "
    "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum gravida "
    "cras eleifend turpis fames primis vulputate ornare sagittis vehicula "
    "praesent dui felis venenatis ultrices proin libero feugiat tristique "
    "accumsan maecenas potenti ultricies habitant morbi senectus netus "
    "suscipit auctor curabitur facilisi cubilia curae hac habitasse platea "
    "dictumst lorem ipsum dolor sit amet consectetur adipiscing elit quisque "
    "faucibus ex sapien vitae pellentesque sem placerat in id cursus mi "
    "pretium tellus duis convallis tempus leo eu aenean sed diam urna tempor "
    "pulvinar vivamus fringilla lacus nec metus bibendum egestas iaculis massa "
    "nisl malesuada lacinia integer nunc posuere ut hendrerit semper vel class "
    "aptent taciti sociosqu ad litora torquent per conubia nostra inceptos "
    "himenaeos orci varius natoque penatibus et magnis dis parturient montes "
    "nascetur ridiculus mus donec rhoncus eros lobortis nulla molestie mattis "
    "scelerisque maximus eget fermentum odio phasellus non purus est efficitur "
    "laoreet mauris pharetra vestibulum fusce dictum risus blandit quis "
    "suspendisse aliquet nisi sodales consequat magna ante condimentum neque "
    "at luctus nibh finibus facilisis dapibus etiam interdum tortor ligula "
    "congue sollicitudin erat viverra ac tincidunt nam porta elementum a enim "
    "euismod quam justo lectus commodo augue arcu dignissim velit aliquam "
    "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum gravida "
    "cras eleifend turpis fames primis vulputate ornare sagittis vehicula "
    "praesent dui felis venenatis ultrices proin libero feugiat tristique "
    "accumsan maecenas potenti ultricies habitant morbi senectus netus "
    "suscipit auctor curabitur facilisi cubilia curae hac habitasse platea "
    "dictumst lorem ipsum dolor sit amet consectetur adipiscing elit quisque "
    "faucibus ex sapien vitae pellentesque sem placerat in id cursus mi "
    "pretium tellus duis convallis tempus leo eu aenean sed diam urna tempor "
    "pulvinar vivamus fringilla lacus nec metus bibendum egestas iaculis massa "
    "nisl malesuada lacinia integer nunc posuere ut hendrerit semper vel class "
    "aptent taciti sociosqu ad litora torquent per conubia nostra inceptos "
    "himenaeos orci varius natoque penatibus et magnis dis parturient montes "
    "nascetur ridiculus mus donec rhoncus eros lobortis nulla molestie mattis "
    "scelerisque maximus eget fermentum odio phasellus non purus est efficitur "
    "laoreet mauris pharetra vestibulum fusce dictum risus blandit quis "
    "suspendisse aliquet nisi sodales consequat magna ante condimentum neque "
    "at luctus nibh finibus facilisis dapibus etiam interdum tortor ligula "
    "congue sollicitudin erat viverra ac tincidunt nam porta elementum a enim "
    "euismod quam justo lectus commodo augue arcu dignissim velit aliquam "
    "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum gravida "
    "cras eleifend turpis fames primis vulputate ornare sagittis vehicula "
    "praesent dui felis venenatis ultrices proin libero feugiat tristique "
    "accumsan maecenas potenti ultricies habitant morbi senectus netus "
    "suscipit auctor curabitur facilisi cubilia curae hac habitasse platea "
    "dictumst lorem ipsum dolor sit amet consectetur adipiscing elit quisque "
    "faucibus ex sapien vitae pellentesque sem placerat in id cursus mi "
    "pretium tellus duis convallis tempus leo eu aenean sed diam urna tempor "
    "pulvinar vivamus fringilla lacus nec metus bibendum egestas iaculis massa "
    "nisl malesuada lacinia integer nunc posuere ut hendrerit semper vel class "
    "aptent taciti sociosqu ad litora torquent per conubia nostra inceptos "
    "himenaeos orci varius natoque penatibus et magnis dis parturient montes "
    "nascetur ridiculus mus donec rhoncus eros lobortis nulla molestie mattis "
    "scelerisque maximus eget fermentum odio phasellus non purus est efficitur "
    "laoreet mauris pharetra vestibulum fusce dictum risus blandit quis "
    "suspendisse aliquet nisi sodales consequat magna ante condimentum neque "
    "at luctus nibh finibus facilisis dapibus etiam interdum tortor ligula "
    "congue sollicitudin erat viverra ac tincidunt nam porta elementum a enim "
    "euismod quam justo lectus commodo augue arcu dignissim velit aliquam "
    "imperdiet mollis nullam volutpat porttitor ullamcorper rutrum gravida "
    "cras eleifend turpis fames primis vulputate ornare sagittis vehicula "
    "praesent dui felis venenatis ultrices proin libero feugiat tristique "
    "accumsan maecenas potenti ultricies habitant morbi senectus netus "
    "suscipit auctor curabitur facilisi cubilia curae hac habitasse platea "
    "dictumst lorem ipsum dolor sit amet consectetur adipiscing elit quisque "
    "faucibus ex sapien vitae pellentesque sem placerat in id cursus mi "
    "pretium tellus duis convallis tempus leo eu aenean sed diam urna tempor "
    "pulvinar vivamus fringilla lacus nec metus bibendum egestas iaculis massa "
    "nisl malesuada lacinia integer nunc posuere ut hendrerit semper vel class "
    "aptent taciti sociosqu ad litora torquent per conubia nostra inceptos "
    "himenaeos orci varius natoque penatibus et.";

inline const char* var2 = "Test short aTest short aaaaaaaaaaaaaaaaaaaaaaaaTest a b c d / www\npc/Test.ext";
inline const char* var9 = "Test short aTest short aaaaaaaaaaaaaaaaaaaaaaaaTest a b c d / www\npc/Test.exd";


inline const char* var3 =
    "Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus "
    "ex sapien vitae pellentesque sem placerat in id cursus mi pretium tellus "
    "duis convallis tempus leo eu aenean sed diam urna tempor pulvinar vivamus "
    "fringilla lacus nec metus bibendum egestas iaculis massa nisl malesuada "
    "lacinia integer nunc posuere ut hendrerit semper vel class aptent taciti "
    "sociosqu ad litora torquent per conubia nostra inceptos himenaeos orci "
    "varius natoque penatibus et magnis dis parturient montes nascetur";

inline const char* var4 =
    "Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus "
    "ex sapien vitae pellentesque sem placerat in id cursus mi pretium tellus "
    "duis convallis tempus leo eu aenean sed diam urna tempor pulvinar vivamus "
    "fringilla lacus nec metus bibendum egestas iaculis massa nisl malesuada "
    "lacinia integer nunc posuere ut hendrerit semper vel class aptent taciti "
    "sociosqu ad litora torquent per conubia nostra inceptos himenaeos orci "
    "varius natoque penatibus et magnis dis montes parturient nascetur";

inline const char* var5 = "resourceexttssxx\\";

inline const char* var6 = "RN01_Sainthaven_A_GoddessStatue_Renew_Waterfall.skn";
inline const char* var7 = "RN01_Sainthaven_A_GoddessStatue_Renew_Waterfall.skx";


#endif
